### ISSUE TITLE
Create read APIs to populate the merchant frontend

### ISSUE THREAD

**Issue by littlejohntj** [solana-labs/solana-payments-app#22]
We've identified three main APIs that we can have to populate the merchant portal. 

/merchant-info
/transactions
/refunds 

We should expose each route and do the following

1. Validate the JWT included in the header 
2. Identify the merchant 
3. Make the relevant database queries ( we can wait on this for now til the database tables get populated )
4. format the data in a flat way that can easily be consumed by the merchant portal

The fields from the response should be as follows:

/merchant-info
- name: string
- receivingWallet: string | null
- isVerified: bool
- acceptedToS: bool
- hasClosedSetUp: bool

/transactions?page=<Int>
- shopifyId: string
- date: string
- status: string
- amount: number
- tx: string
- tx_url: string

/refunds?page=<Int>
- shopifyId: string
- date: string
- status: string
- refundAmount: string
- totalAmount: string
- txUrl: string | null
- isOpen: bool

We should also include pagination query parameter as well as a total count at the top level

**Comment by harshasomisetty** [comment]
https://github.com/solana-labs/solana-payments-app/pull/18

So far created the api routes, validating JWT and merchant, querying data, and created appropriate prisma models & api handlers for the new routes.

Will work on pagination soon, guessing it should query the latest datapts
