### ISSUE TITLE
Need to handle different types of wallet inputs on the merchant portal.

### ISSUE THREAD

**Issue by littlejohntj** [solana-labs/solana-payments-app#311]
So right now, on the merchant portal, merchant's are able to paste in a wallet address that will have their funds directed towards. The only check that exists right now is that the string can be turned into a pub key and this is done on the front end. We should do better to handle this in the backend and on the user experience. Here is what I'm thinking.

- In the merchant-update api that the merchant portal uses to set a merchant's wallet address, we add logic to check if the pubkey is either:

1. A native system program account ( like your phantom wallet )
2. A USDC token account ( they could be an advanced user and think this is okay or they could get this value from a custodial solution like Circle )

Anything other than these types will be rejected and we will show them an error. This error should be clickable and show them a modal that explains the types of wallets they are able to use.

If the value is a native system program account, then we will use it basically how we are already. Keeping that as their "wallet address" and when they receive funds, the transaction request server will derive their associated token account and direct USDC there.

To handle cases that are USDC token accounts, we will add a new field to the database called: 'tokenAddress', this will be another optional field. Then we can set this when a merchant tries to update using this type of wallet address. We will have to make updates to things like "does the merchant have a wallet" and "how to build this transaction" but I think the changes will be fairly localized.

I've already started experimenting with RPC getAccountInfo request and it appears we can pull this data fairly easily. Look here for the spec: https://docs.solana.com/api/http#getaccountinfo

result.value.owner should do well to tell us if its a native account or token account and then for token accounts we can use result.value.data.parsed.info.mint should confirm its a USDC account.

**Comment by jordansexton** [comment]
Yeah, I think it makes sense to store a `walletAddress` and `usdcAddress` per user. Maybe wouldn't call it `tokenAddress` unless you plan to mix different kinds of receivable tokens in the field, which sounds unlikely (and also then would require having a `tokenMint` unless you fetch data every time it's used). You can also store `usdcAddress` for any `walletAddress` users after deriving it the first time.

**Comment by littlejohntj** [comment]
I plan to add dynamic settlement tokens in the future. Just hardcoded both sides for this release. Not sure exactly where in the roadmap it is, I could see just doing dynamic paying tokens first but i'd imagine it'll be the same effort to add merchant side as well in that release. 

If I go with that, I like adding tokenMint now to start working that into the codebase.

@jordansexton any worries about RPC spec updates that could break these data spec assumptions?

**Comment by jordansexton** [comment]
Hmm but if a merchant can receive multiple tokens, you'll want a separate table for all that anyway, right?

**Comment by littlejohntj** [comment]
I imagine merchants would accept a single token and we would handle swaps using Jupiter. 

Merchant accepts token A
User pays with token B

if A != B, add a swap instruction from A -> B with Jupiters exact amount swap API

database design is slightly lacking in this project in general though @jordansexton would love for you to peep it and let me know if you have any recs

**Comment by steveluscher** [comment]
I don't think we should make people think. Instead:

* IF address is owned by the system program
  * THEN compute the USDC ATA owned by that address and use that
* IF address is owned by the token program
  * AND mint matches the settlement mint
  * THEN use it verbatim

That way the tokens go to the right place no matter if the user pastes their ‘wallet’ address or the address of a USDC ATA.

Backpack took a different position. For reference they refuse to accept any destination address that doesn't belong to the system program. You can't paste a USDC ATA in as the destination address.
