### ISSUE TITLE
Merchant UI Sidebar scrolls up and is out of the window

### ISSUE THREAD

**Issue by harshasomisetty** [solana-labs/solana-payments-app#369]
When the page is very long and the user scrolls, the sidebar goes out of view. Might need to change the sidebar to sticky or similar

<img width="1493" alt="Screenshot 2023-06-22 at 5 25 01 PM" src="https://github.com/solana-labs/solana-payments-app/assets/25572511/f4da5e0e-e656-452b-9b9a-318f2eb48a63">

<img width="1491" alt="Screenshot 2023-06-22 at 5 25 18 PM" src="https://github.com/solana-labs/solana-payments-app/assets/25572511/d6adf637-5c69-4bbb-bd86-69a8c8ce0e67">

<img width="1488" alt="Screenshot 2023-06-22 at 5 25 35 PM" src="https://github.com/solana-labs/solana-payments-app/assets/25572511/a684da67-9f07-4832-b6f8-3c9af8da67d3">

**Comment by Wholesomebruh** [comment]
Hey , what are the steps to reproduce?
